---
title: "R Notebook"
output: html_notebook
---



```{r}
library(tidyverse)
library(lubridate)
library(zoo)
library(gghighlight)
library(ggtext)
library(ggthemes)
library(corrr)
```

```{r}
custom_theme <- theme_tufte() +
  theme(
    strip.text = element_text(
      family = 'American Typewriter',
      size = 25,
      hjust = 0.5
    ),
    strip.text.x = element_text(margin = margin(1, 0.5, 0.2, 0.5, "cm")),
    plot.caption = element_text(
      #family = 'B Mitra',
      size = 10,
      margin = margin(1.5, 0, 1.5, 0, "cm"),
    ),
    plot.title = element_text(
      family = 'American Typewriter',
      face = "bold",
      size = 35,
      margin = margin(1, 0, 1, 0, "cm"),
      hjust = 0,
      vjust = -0.5
    ),
    
    plot.subtitle = element_text(
      family = 'American Typewriter',
      face = "bold",
      size = 20,
      color = 'gray40',
      margin = margin(1, 0, 1, 0, "cm"),
      hjust = 0
    ),
    axis.text.y.left = element_text(family = 'American Typewriter', size = 16),
    axis.text.x = element_text(
      family = 'American Typewriter',
      hjust = 0.5,
      size = 16,
    ),
    plot.background = element_rect(fill = '#FCF0E1'),
    axis.line.y =  element_line(linetype = 'dashed'),
    panel.grid.major.y =  element_line(linetype = 'dashed', color = 'gray60'),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()

  )

theme_set(custom_theme)
```






```{r}
nl_data <-read_csv('https://raw.githubusercontent.com/J535D165/CoronaWatchNL/master/data/rivm_corona_in_nl.csv')
nl_data
```
```{r}
cities <- c('Tilburg','Breda','Utrecht','Amsterdam','Rotterdam',
            'Den Haag', 'Enschede','Delft','Eindhoven','Nijmegen',
            'Maastricht','Zwolle')
```



```{r}

cities_ordered <- nl_data %>% 
    filter(Gemeentenaam %in% cities) %>% 
  #filter(Provincienaam == 'Zuid-Holland') %>% 
  group_by(Gemeentenaam) %>% 
  summarize(sum_aantal = sum(Aantal)) %>% 
  arrange(desc(sum_aantal)) %>%
  select(Gemeentenaam) %>% 
  pull() 

cities_ordered
cities_ordered <- factor(cities,levels = cities_ordered)


cities_df <- nl_data %>% 
  filter(Gemeentenaam %in% cities_ordered) %>% 
  mutate(Datum = as_date(Datum)) %>% 
  rename(City = Gemeentenaam)




dates <- cities_df %>% 
  select(Datum) %>% 
  distinct(Datum) %>% 
  pull()


complete_grid <- expand.grid(dates,cities, KEEP.OUT.ATTRS = TRUE, stringsAsFactors = TRUE)
names(complete_grid) <- c('Datum','City')
nl_ds <- complete_grid %>% left_join(cities_df %>% select(Datum,City,Aantal) ,by=c('Datum','City'))#%>% 
  #


nl_ds_vis <- nl_ds %>% 
  arrange(Datum,City) %>% 
  group_by(Datum,City) %>% 
  mutate(Aantal = as.integer(Aantal ),
         
  Aantal=na.locf0(Aantal)) %>% 
  replace(is.na(.), 0)
```

```{r fig.height=25,fig.width=20}
nl_ds_vis %>% 
  ggplot(aes(Datum,Aantal)) +
  
  geom_point(color = 'indianred',size =3,) +
  geom_line(color = '#E7962A',size = 1.5,alpha = 1) +
  geom_area(fill = '#F6DAB4',color = '#F6DAB4' ) +
  #scale_x_continuous(breaks = c(10,15,20),labels = c(ticks_2,
  #                                                   'اسنفد 25',
  #                                                   ticks_) )+
  facet_wrap(~fct_reorder(City,-Aantal),ncol = 3)
```



```{r fig.height=25,fig.width=20}

nl_ds_vis %>% 
  ggplot(aes(Datum,Aantal,color = City,fill = City)) +
  geom_line(color = 'indianred',size = 1.5,alpha = 1) +
  geom_point(color = 'indianred',size = 3) +
  gghighlight( use_direct_label = FALSE,unhighlighted_params = list(size = 1.5,width = 0.5,color ='#F6DAB4',alpha  = 0.7)) +
  facet_wrap(~fct_reorder(City,-Aantal),ncol = 3 ) +
  labs(title =  'Covid-19 in The Netherlands',
       subtitle  = 'The total number of people who have been tested positive based on data provided by the Dutch government',
       caption = 'Source: RIVM\n
       Data: https://github.com/J535D165/CoronaWatchNL\n
       Visualization: mcnakhaee.com') +
  theme(legend.position ='none') 
  
```

